export const animeLibrary = [
  {
    id: "one-punch-man",
    title: "One Punch Man",
    subtitle: "The Hero For Fun",
    poster: "img/Saitama Poster__ One Punch Man.jpeg",
    categories: ["Shonen", "Action", "Comedy"],
    rating: "9.1",
    year: "2015",
    seasons: "2 Seasons",
    duration: "24m / episode",
    status: "Streaming Now",
    trailerLabel: "Watch Trailer",
    synopsis:
      "Saitama trained so hard that he became the strongest hero alive, but now every fight ends in one punch. Between grocery sales and universe-level threats, he searches for a worthy challenge.",
    cast: ["Makoto Furukawa", "Kaito Ishikawa", "Aoi Yuki"],
    streamUrl: "https://archive.org/details/onepunchmanchapters8595",
  },
  {
    id: "death-note",
    title: "Death Note",
    subtitle: "A Battle of Genius Minds",
    poster: "img/Death Note.jpeg",
    categories: ["Psychological", "Thriller", "Mystery"],
    rating: "9.4",
    year: "2006",
    seasons: "1 Season",
    duration: "23m / episode",
    status: "Fan Favorite",
    trailerLabel: "Mind Game Trailer",
    synopsis:
      "When Light Yagami finds a notebook that can kill anyone whose name is written in it, he starts reshaping the world. Detective L appears, turning the story into a legendary mind war.",
    cast: ["Mamoru Miyano", "Kappei Yamaguchi", "Shido Nakamura"],
    streamUrl: "#",
  },
  {
    id: "wind-breaker",
    title: "Wind Breaker",
    subtitle: "Street Legends Rise",
    poster: "img/Windbreaker (Anime).jpeg",
    categories: ["Action", "Delinquent", "School"],
    rating: "8.7",
    year: "2024",
    seasons: "1 Season",
    duration: "24m / episode",
    status: "Fresh Drop",
    trailerLabel: "Street Fight Trailer",
    synopsis:
      "Haruka Sakura arrives at Furin High looking to fight the strongest, but discovers a team that protects their town. Rivalries, loyalty, and top-tier action drive this modern street saga.",
    cast: ["Yuma Uchida", "Nobunaga Shimazaki", "Shoya Chiba"],
    streamUrl: "#",
  },
  {
    id: "spy-x-family",
    title: "Spy x Family",
    subtitle: "A Fake Family, Real Feelings",
    poster: "img/Season 2 Key Visual 1 _ October 7 Premiere.jpeg",
    categories: ["Slice of Life", "Comedy", "Action"],
    rating: "9.0",
    year: "2022",
    seasons: "2 Seasons",
    duration: "24m / episode",
    status: "Top Pick",
    trailerLabel: "Family Mission Trailer",
    synopsis:
      "A spy, an assassin, and a telepath pretend to be a normal family while hiding dangerous secrets. Their chaotic home life is equal parts wholesome and explosive.",
    cast: ["Takuya Eguchi", "Saori Hayami", "Atsumi Tanezaki"],
    streamUrl: "#",
  },
  {
    id: "tokyo-revengers",
    title: "Tokyo Revengers",
    subtitle: "Rewrite the Future",
    poster: "img/TOKYO REVENGERS 2.jpeg",
    categories: ["Shonen", "Action", "Sci-Fi"],
    rating: "8.8",
    year: "2021",
    seasons: "3 Seasons",
    duration: "24m / episode",
    status: "Binge Ready",
    trailerLabel: "Time Leap Trailer",
    synopsis:
      "Takemichi can leap through time to save the people he loves and stop gang wars before they happen. Every mission demands courage, sacrifice, and impossible choices.",
    cast: ["Yuki Shin", "Yuu Hayashi", "Azumi Waki"],
    streamUrl: "#",
  },
];

export const animeById = Object.fromEntries(
  animeLibrary.map((anime) => [anime.id, anime]),
);
