export const animeLibrary = [
  {
    id: "one-punch-man",
    title: "One Punch Man",
    subtitle: "The Hero For Fun",
    poster: "img/Saitama Poster__ One Punch Man.jpeg",
    categories: ["Shonen", "Action", "Comedy"],
    rating: "9.1",
    year: "2015",
    seasons: "2 Seasons",
    duration: "24m / episode",
    status: "Streaming Now",
    trailerLabel: "Watch Trailer",
    synopsis:
      "Saitama trained so hard that he became the strongest hero alive, but now every fight ends in one punch. Between grocery sales and universe-level threats, he searches for a worthy challenge.",
    cast: ["Makoto Furukawa", "Kaito Ishikawa", "Aoi Yuki"],
    streamUrl: "https://archive.org/details/onepunchmanchapters8595",
  },
  {
    id: "death-note",
    title: "Death Note",
    subtitle: "A Battle of Genius Minds",
    poster: "img/Death Note.jpeg",
    categories: ["Psychological", "Thriller", "Mystery"],
    rating: "9.4",
    year: "2006",
    seasons: "1 Season",
    duration: "23m / episode",
    status: "Fan Favorite",
    trailerLabel: "Mind Game Trailer",
    synopsis:
      "When Light Yagami finds a notebook that can kill anyone whose name is written in it, he starts reshaping the world. Detective L appears, turning the story into a legendary mind war.",
    cast: ["Mamoru Miyano", "Kappei Yamaguchi", "Shido Nakamura"],
    streamUrl: "#",
  },
  {
    id: "wind-breaker",
    title: "Wind Breaker",
    subtitle: "Street Legends Rise",
    poster: "img/Windbreaker (Anime).jpeg",
    categories: ["Action", "Delinquent", "School"],
    rating: "8.7",
    year: "2024",
    seasons: "1 Season",
    duration: "24m / episode",
    status: "Fresh Drop",
    trailerLabel: "Street Fight Trailer",
    synopsis:
      "Haruka Sakura arrives at Furin High looking to fight the strongest, but discovers a team that protects their town. Rivalries, loyalty, and top-tier action drive this modern street saga.",
    cast: ["Yuma Uchida", "Nobunaga Shimazaki", "Shoya Chiba"],
    streamUrl: "#",
  },
  {
    id: "spy-x-family",
    title: "Spy x Family",
    subtitle: "A Fake Family, Real Feelings",
    poster: "img/Season 2 Key Visual 1 _ October 7 Premiere.jpeg",
    categories: ["Slice of Life", "Comedy", "Action"],
    rating: "9.0",
    year: "2022",
    seasons: "2 Seasons",
    duration: "24m / episode",
    status: "Top Pick",
    trailerLabel: "Family Mission Trailer",
    synopsis:
      "A spy, an assassin, and a telepath pretend to be a normal family while hiding dangerous secrets. Their chaotic home life is equal parts wholesome and explosive.",
    cast: ["Takuya Eguchi", "Saori Hayami", "Atsumi Tanezaki"],
    streamUrl: "#",
  },
  {
    id: "tokyo-revengers",
    title: "Tokyo Revengers",
    subtitle: "Rewrite the Future",
    poster: "img/TOKYO REVENGERS 2.jpeg",
    categories: ["Shonen", "Action", "Sci-Fi"],
    rating: "8.8",
    year: "2021",
    seasons: "3 Seasons",
    duration: "24m / episode",
    status: "Binge Ready",
    trailerLabel: "Time Leap Trailer",
    synopsis:
      "Takemichi can leap through time to save the people he loves and stop gang wars before they happen. Every mission demands courage, sacrifice, and impossible choices.",
    cast: ["Yuki Shin", "Yuu Hayashi", "Azumi Waki"],
    streamUrl: "#",
  },
  {
    id: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    subtitle: "Curses & Sorcery",
    poster:
      "img/Jutsu kaisen lover !!!!_ GATHER HER IN THE COMMENTS NOW !!!.jpeg",
    categories: ["Supernatural", "Action", "Dark Fantasy"],
    rating: "9.2",
    year: "2020",
    seasons: "2 Seasons",
    duration: "24m / episode",
    status: "Trending",
    trailerLabel: "Domain Expansion",
    synopsis:
      "Yuji Itadori swallows a cursed talisman—the finger of a demon—and becomes cursed himself. He enters a shaman's school to be able to locate the demon's other body parts and thus exorcise himself.",
    cast: ["Junya Enoki", "Yuchida Yuma", "Asami Seto"],
    streamUrl: "#",
  },
  {
    id: "one-piece",
    title: "One Piece",
    subtitle: "Set Sail for the Grand Line",
    poster: "img/e76d204e-f9e5-490c-b80a-2ff4b242a5ca.jpeg",
    categories: ["Adventure", "Shonen", "Fantasy"],
    rating: "9.5",
    year: "1999",
    seasons: "20+ Seasons",
    duration: "24m / episode",
    status: "Classic",
    trailerLabel: "Adventure Trailer",
    synopsis:
      "Monkey D. Luffy refuses to let anyone or anything stand in the way of his quest to become the King of All Pirates. With a course charted for the treacherous waters of the Grand Line and beyond, this is one captain who'll never drop anchor.",
    cast: ["Mayumi Tanaka", "Kazuya Nakai", "Akemi Okamura"],
    streamUrl: "#",
  },
  {
    id: "dragon-ball-z",
    title: "Dragon Ball Z",
    subtitle: "The Legendary Super Saiyan",
    poster: "img/Affiche métal DragonBall Z.jpeg",
    categories: ["Action", "Shonen", "Martial Arts"],
    rating: "9.3",
    year: "1989",
    seasons: "9 Seasons",
    duration: "24m / episode",
    status: "Legendary",
    trailerLabel: "Power Up Trailer",
    synopsis:
      "Goku and the Z Fighters defend the Earth against evil threats ranging from aliens and androids to magical creatures and deities. The battles are massive, the stakes are high, and the hair is gold.",
    cast: ["Masako Nozawa", "Ryo Horikawa", "Toshio Furukawa"],
    streamUrl: "#",
  },
  {
    id: "dr-stone",
    title: "Dr. Stone",
    subtitle: "Rebuilding Civilization",
    poster: "img/Dr Stone Season 4 Release Date at Triciallanes.jpeg",
    categories: ["Sci-Fi", "Adventure", "Intellectual"],
    rating: "8.9",
    year: "2019",
    seasons: "4 Seasons",
    duration: "24m / episode",
    status: "New Season",
    trailerLabel: "Science Trailer",
    synopsis:
      "One fateful day, all of humanity was petrified by a blinding flash of light. After several millennia, high schooler Taiju awakens and finds himself lost in a world of statues. However, he is not alone.",
    cast: ["Yusuke Kobayashi", "Makoto Furukawa", "Kana Ichinose"],
    streamUrl: "#",
  },
  {
    id: "kaguya-sama",
    title: "Kaguya-Sama: Love is War",
    subtitle: "Love is a Battlefield",
    poster: "img/Kaguya-Sama _Love Is War_ Poster made by me.jpeg",
    categories: ["Romance", "Comedy", "School"],
    rating: "9.0",
    year: "2019",
    seasons: "3 Seasons",
    duration: "24m / episode",
    status: "Must Watch",
    trailerLabel: "Romance Trailer",
    synopsis:
      "Kaguya Shinomiya and Miyuki Shirogane are two geniuses who stand atop their prestigious academy's student council, making them the elite among elite. But it's lonely at the top and each has fallen for the other.",
    cast: ["Aoi Koga", "Makoto Furukawa", "Konomi Kohara"],
    streamUrl: "#",
  },
  {
    id: "gintama",
    title: "Gintama",
    subtitle: "Samurai & Aliens",
    poster: "img/Gintama.jpeg",
    categories: ["Comedy", "Action", "Sci-Fi"],
    rating: "9.1",
    year: "2006",
    seasons: "10 Seasons",
    duration: "24m / episode",
    status: "Cult Classic",
    trailerLabel: "Comedy Trailer",
    synopsis:
      "In an era where aliens have invaded and taken over feudal Tokyo, a young samurai finds work however he can. A hilarious, action-packed, and often tear-jerking adventure ensues.",
    cast: ["Tomokazu Sugita", "Daisuke Sakaguchi", "Rie Kugimiya"],
    streamUrl: "#",
  },
  {
    id: "persona-3",
    title: "Persona 3 Reload",
    subtitle: "Burn My Dread",
    poster: "img/Persona 3 Reload _ Poster.jpeg",
    categories: ["Supernatural", "Mystery", "School"],
    rating: "8.9",
    year: "2024",
    seasons: "Movie Series",
    duration: "1h 45m",
    status: "Feature Film",
    trailerLabel: "Dark Hour Trailer",
    synopsis:
      "Between one day and the next lies the Dark Hour. During this time, the world stands still, and monsters known as Shadows swarm the city. A group of students awakens to their power to fight them.",
    cast: ["Akira Ishida", "Megumi Toyoguchi", "Kosuke Toriumi"],
    streamUrl: "#",
  },
  {
    id: "naruto",
    title: "Naruto",
    subtitle: "Believe It!",
    poster: "img/download.jpeg",
    categories: ["Shonen", "Adventure", "Ninja"],
    rating: "8.8",
    year: "2002",
    seasons: "9 Seasons",
    duration: "23m / episode",
    status: "Classic",
    trailerLabel: "Ninja Way Trailer",
    synopsis:
      "Naruto Uzumaki, a hyperactive and knuckleheaded ninja, searches for recognition from his peers and dreams of becoming the Hokage, the village leader.",
    cast: ["Junko Takeuchi", "Maile Flanagan", "Kate Higgins"],
    streamUrl: "#",
  },
  {
    id: "darling-in-the-franxx",
    title: "Darling in the Franxx",
    subtitle: "Pilot the Future",
    poster: "img/download (1).jpeg",
    categories: ["Mecha", "Romance", "Drama"],
    rating: "8.5",
    year: "2018",
    seasons: "1 Season",
    duration: "24m / episode",
    status: "Completed",
    trailerLabel: "Mecha Trailer",
    synopsis:
      "In a post-apocalyptic future, young pilots fight against giant monsters known as Klaxosaurs using giant robots called Franxx. Hiro, a former prodigy, finds a new partner in the mysterious Zero Two.",
    cast: ["Yuto Uemura", "Haruka Tomatsu", "Kana Ichinose"],
    streamUrl: "#",
  },
];

export const animeById = Object.fromEntries(
  animeLibrary.map((anime) => [anime.id, anime]),
);
